site_name: Documentação SiProd

theme:
  name: material
  font: Roboto Mono
  lang: pt-BR
  # favicon: images/favicon.png
  features:
    - navigation.indexes
  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/weather-sunny
        name: Modo noturno
    - scheme: slate
      primary: red
      toggle:
        icon: material/weather-night
        name: Modo claro

plugins:
  - search:
      lang: pt

nav:
  - 'Home': 'home/index.md'
  - Web:
    - Cadastros:
      - web/register/register_activities/register_activities.md
      - web/register/register_equipment/register_equipment.md
      - web/register/register_service_release/register_service_release.md
      - web/register/register_electronic_point/register_electronic_point.md
    - Limpar o cache:
      - web/clear_site_data/clear_site_data_chrome.md
      - web/clear_site_data/clear_site_data_edge.md
  - Mobile:
    - mobile/install_app_siprod/install_siprod_app.md

markdown_extensions:
  - admonition
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCxn0h0EOKpYfJ9yewaUVHaQ

copyright: SiProd &copy; 2019 - 2022 | Lindamar Fernandes| Wilkne Maia | Mardone Dias
