site_name: Documentação SiProd

theme:
  name: material
  font: Roboto Mono
  lang: pt-BR
  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/weather-sunny
        name: Modo noturno
    - scheme: slate
      primary: red
      toggle:
        icon: material/weather-night
        name: Modo claro


nav:
  - 'Home': 'index.md'
  - 'Limpar dados de navegação no chrome': 'clear_site_data.md'
  - 'Instalar App SiProd': 'install_siprod_app.md'

markdown_extensions:
  - pymdownx.keys
  - pymdownx.superfences

extra:
  version:
    provider: mike
